---
- name: "Yazi | Install"
  ansible.builtin.package:
    name:
    - yazi
    - ffmpeg
    - p7zip
    - jq
    - poppler
    - fd
    - ripgrep
    - fzf
    - zoxide
    - imagemagick
    state: present
  become: true

