---
- name: "ZSH | Install"
  ansible.builtin.dnf:
    name: "zsh"
    state: present
  become: true

- name: "ZSH | Set Default Shell"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "/bin/zsh"
  become: true
