---
- name: "Kitty | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Kitty | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists and not ansible_host_environment_is_wsl

- name: "Kitty | Create Config Directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    mode: "0755"
    state: directory
  when: not ansible_host_environment_is_wsl

- name: "Kitty | Deploy Config File"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/kitty.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
  when: not ansible_host_environment_is_wsl
