---
- name: "Starship | Check if Starship is installed"
  ansible.builtin.shell:
    cmd: "command -v starship"
  ignore_errors: true
  register: starship_installed

- name: "Starship | Install"
  block:
    - name: "Download Install Script"
      ansible.builtin.get_url:
        url: "https://starship.rs/install.sh"
        dest: "/tmp/starship-install.sh"
        mode: '0755'
    - name: "Install"
      ansible.builtin.shell: "/tmp/starship-install.sh -y"
  when: starship_installed.rc != 0

