---
- name: "Neovim | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Neovim | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Neovim | Config folder"
  ansible.builtin.git:
    repo: "https://github.com/Juangr4/nvim.git"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    clone: yes
    update: yes

- name: "Neovim | Setup alias inside .bashrc"
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: "alias n="
    line: "alias n='nvim'"
    state: present
    insertbefore: EOF

