---
- name: "Bat | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Bat | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Bat | Setup alias inside .bashrc"
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: "alias cat="
    line: "alias cat='bat'"
    state: present
    insertbefore: EOF
