---
- name: "Zellij | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Zellij | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists and ansible_host_environment_is_wsl

- name: "Zellij | Deploy Zellij Config Files"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/zellij"
    dest: "{{ ansible_user_dir }}/.config"
  when: ansible_host_environment_is_wsl

- name: "Zellij | Add zellij inside .bashrc"
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: 'if [[ "${ZELLIJ}" != 0 ]]; then /usr/local/bin/zellij; fi'
    regexp: 'if [[ "${ZELLIJ}" != 0 ]]; then /usr/local/bin/zellij; fi'
    state: present
  when: ansible_host_environment_is_wsl

